### ISSUE TITLE
Constant buffer remapping

### ISSUE THREAD

**Issue by bhouse-microsoft** [Microsoft/graphics-driver-samples#16]
The constant buffer must be laid out to conform to how the constants will be read by the shader(s).

The work to provide the layout by the shaders has been done.  The driver now must consume the shader layout and compose the constant buffer placing the composed buffer inline with the command buffer for consumption by the shader at execution.

**Comment by indygit** [comment]
Finished. UMD now utilizes remapping info from our shader compiler.
