### ISSUE TITLE
Shader compiler support for Dolphin

### ISSUE THREAD

**Issue by bhouse-microsoft** [Microsoft/graphics-driver-samples#17]
The dolphin demo will require byte code support.

This includes support for instructions  madd, maddot3, maddot 4.  General (non 1.0) w support.  Suport for the modifiers neg, abs, negabs.

Hideyuki is in the process of adding this support now.

**Comment by hideyukn88** [comment]
Completed except abs, negabs as those are not used in Dolphin.

**Comment by hideyukn88** [comment]
Completed support for abs, absneg as well.
