### ISSUE TITLE
SetScissorRects support needs to be expanded

### ISSUE THREAD

**Issue by jeffwick-msft** [Microsoft/graphics-driver-samples#36]
Further support for SetScissorRects needs to be implemented in the Raspberry Pi driver in order to support Windows Shell (SIHost). Currently, the assert in RosUmdDevice::SetScissorRects is being hit with parameters:

ClearScissorRects = 0x10 = all clear.

and
 
NumScissorRects = 1
ClearScissorRects = 0xf

**Comment by hideyukn88** [comment]
Fixed.
