### ISSUE TITLE
VC4 Translate_VS needs support for D3D10_SB_OPCODE_IADD

### ISSUE THREAD

**Issue by jeffwick-msft** [Microsoft/graphics-driver-samples#38]
Support for D3D10_SB_OPCODE_IADD in rosumd!Vc4Shader::Translate_VS needs to be implemented, to support Windows Shell (SIHost).

**Comment by indygit** [comment]
For both this issue and #37 , I think the upper layer rendering code should be D2D/XAML.
So we should be able to run VC4 driver in render-only mode, get D2D/XAMPL work well and then switch back to full-driver mode and check if rendering from SiHost works OK.

**Comment by hideyukn88** [comment]
Fixed
