### ISSUE TITLE
Implement basic validation of command submission to hardware on raspberry pi

### ISSUE THREAD

**Issue by bhouse-microsoft** [Microsoft/graphics-driver-samples#9]
This test should submit a GPU operation upon receiving a DMA command buffer submission.  The driver should be notified by hardware when the GPU operation is completed.  Upon notification of GPU command completion, the driver should notify DXGKrnl of the DMA command buffer completion as appropriate.

Ideally, the GPU operation should be some very trivial operation (such as a NOP command submission).

This should be the first step towards handling an actual GPU submission.

**Comment by bhouse-microsoft** [comment]
I believe this work is complete.  Assigning to Indy to comment and close.

**Comment by indygit** [comment]
Correct. We can run Cubetest and DolphineTests, so command submission is definitely working.
